### PR TITLE
Make Vector3 module public

### PR DESCRIPTION
**Pull request by ghost**
I saw that your crate is not presenting anything on docs.rs and it appears that's due to you not providing the vector3 module as public.

If the module isn't public then you can't use it.

### CODE REVIEW

**Comment by ghost** [comment]
I've also bumped the version number to 1.1.2 however you can choose to revert that.

**Comment by ghost** [comment]
I've built a local version of the documentation on my branch using `cargo doc --open -p vector3` and the results [speak for themselves](https://colean.cc/doc/vector3/).

**Comment by ghost** [comment]
I see that you have made the module public now, I am closing this PR.

**Comment by local-interloper** [comment]
Sorry for the lack of feedback man, I was probably busy with college or some shit. Thanks for pointing it out tho and I'm glad the issue was resolved!

**Pull request closed without merging**
